import { KPIData } from "@/lib/types";
import { ContentItem, ContentTemplate } from "./types";

export const contentKPIs: KPIData[] = [
  { label: "本月生成数", value: 328, trend: "up", trendPercent: 15.2, icon: "FileText", format: "number" },
  { label: "已发布数", value: 156, trend: "up", trendPercent: 8.7, icon: "Send", format: "number" },
  { label: "待审核数", value: 24, trend: "down", trendPercent: 5.3, icon: "Clock", format: "number" },
  { label: "平均互动率", value: 4.8, trend: "up", trendPercent: 1.2, icon: "Heart", format: "percent" },
];

export const mockContents: ContentItem[] = [
  {
    id: "c1",
    title: "春季穿搭灵感｜5套通勤look轻松搞定",
    body: "春天来了，是时候更新你的衣橱了...",
    platform: "xiaohongshu",
    content_type: "carousel",
    status: "published",
    engagement: { views: 12500, likes: 890, comments: 156, shares: 234 },
    tags: ["穿搭", "春季", "通勤"],
    scheduled_at: null,
    published_at: "2026-03-20T10:00:00Z",
    created_at: "2026-03-18T08:00:00Z",
    updated_at: "2026-03-20T10:00:00Z",
  },
  {
    id: "c2",
    title: "爆款无线耳机开箱测评｜音质炸裂",
    body: "今天给大家带来一款超高性价比的无线耳机...",
    platform: "tiktok",
    content_type: "short_video",
    status: "published",
    engagement: { views: 45000, likes: 3200, comments: 478, shares: 890 },
    tags: ["数码", "耳机", "测评"],
    scheduled_at: null,
    published_at: "2026-03-19T14:00:00Z",
    created_at: "2026-03-17T09:00:00Z",
    updated_at: "2026-03-19T14:00:00Z",
  },
  {
    id: "c3",
    title: "家居好物分享｜让小空间变大的收纳神器",
    body: "小户型也能住出幸福感，这些收纳神器你一定需要...",
    platform: "xiaohongshu",
    content_type: "image_post",
    status: "scheduled",
    engagement: { views: 0, likes: 0, comments: 0, shares: 0 },
    tags: ["家居", "收纳", "好物"],
    scheduled_at: "2026-03-28T09:00:00Z",
    published_at: null,
    created_at: "2026-03-22T11:00:00Z",
    updated_at: "2026-03-22T11:00:00Z",
  },
  {
    id: "c4",
    title: "Summer Sale Campaign - Up to 50% Off",
    body: "Don't miss our biggest summer sale event...",
    platform: "instagram",
    content_type: "carousel",
    status: "pending",
    engagement: { views: 0, likes: 0, comments: 0, shares: 0 },
    tags: ["促销", "夏季", "折扣"],
    scheduled_at: null,
    published_at: null,
    created_at: "2026-03-24T15:00:00Z",
    updated_at: "2026-03-24T15:00:00Z",
  },
  {
    id: "c5",
    title: "新品预告｜限量联名款即将上线",
    body: "期待已久的联名款终于要来了...",
    platform: "tiktok",
    content_type: "short_video",
    status: "draft",
    engagement: { views: 0, likes: 0, comments: 0, shares: 0 },
    tags: ["新品", "联名", "限量"],
    scheduled_at: null,
    published_at: null,
    created_at: "2026-03-25T10:00:00Z",
    updated_at: "2026-03-25T10:00:00Z",
  },
  {
    id: "c6",
    title: "护肤小课堂｜敏感肌换季护理指南",
    body: "换季期间敏感肌如何正确护肤...",
    platform: "xiaohongshu",
    content_type: "article",
    status: "published",
    engagement: { views: 8900, likes: 567, comments: 89, shares: 123 },
    tags: ["护肤", "敏感肌", "换季"],
    scheduled_at: null,
    published_at: "2026-03-15T08:00:00Z",
    created_at: "2026-03-13T14:00:00Z",
    updated_at: "2026-03-15T08:00:00Z",
  },
  {
    id: "c7",
    title: "Best Kitchen Gadgets for 2026",
    body: "Transform your cooking experience with these must-have gadgets...",
    platform: "amazon",
    content_type: "article",
    status: "published",
    engagement: { views: 6700, likes: 234, comments: 45, shares: 78 },
    tags: ["厨房", "好物", "推荐"],
    scheduled_at: null,
    published_at: "2026-03-18T12:00:00Z",
    created_at: "2026-03-16T09:00:00Z",
    updated_at: "2026-03-18T12:00:00Z",
  },
  {
    id: "c8",
    title: "独立站春季上新｜精选20款新品",
    body: "春季焕新，精心挑选20款高品质新品...",
    platform: "independent",
    content_type: "article",
    status: "scheduled",
    engagement: { views: 0, likes: 0, comments: 0, shares: 0 },
    tags: ["上新", "春季", "精选"],
    scheduled_at: "2026-03-29T10:00:00Z",
    published_at: null,
    created_at: "2026-03-23T16:00:00Z",
    updated_at: "2026-03-23T16:00:00Z",
  },
  {
    id: "c9",
    title: "周末穿搭vlog｜一衣多穿的秘密",
    body: "一件基础款如何搭配出不同风格...",
    platform: "tiktok",
    content_type: "short_video",
    status: "published",
    engagement: { views: 32000, likes: 2100, comments: 320, shares: 560 },
    tags: ["穿搭", "vlog", "时尚"],
    scheduled_at: null,
    published_at: "2026-03-21T16:00:00Z",
    created_at: "2026-03-19T12:00:00Z",
    updated_at: "2026-03-21T16:00:00Z",
  },
  {
    id: "c10",
    title: "Shopify店铺优化攻略｜转化率提升30%",
    body: "通过这些优化技巧让你的Shopify店铺业绩翻倍...",
    platform: "shopify",
    content_type: "article",
    status: "pending",
    engagement: { views: 0, likes: 0, comments: 0, shares: 0 },
    tags: ["电商", "优化", "转化率"],
    scheduled_at: null,
    published_at: null,
    created_at: "2026-03-26T09:00:00Z",
    updated_at: "2026-03-26T09:00:00Z",
  },
  {
    id: "c11",
    title: "健身打卡Day30｜居家训练全记录",
    body: "坚持30天居家健身的真实变化...",
    platform: "instagram",
    content_type: "story",
    status: "rejected",
    engagement: { views: 0, likes: 0, comments: 0, shares: 0 },
    tags: ["健身", "打卡", "居家"],
    scheduled_at: null,
    published_at: null,
    created_at: "2026-03-22T07:00:00Z",
    updated_at: "2026-03-23T10:00:00Z",
  },
  {
    id: "c12",
    title: "美食探店｜藏在巷子里的宝藏咖啡馆",
    body: "今天带大家探访一家超隐秘的咖啡馆...",
    platform: "xiaohongshu",
    content_type: "image_post",
    status: "draft",
    engagement: { views: 0, likes: 0, comments: 0, shares: 0 },
    tags: ["美食", "探店", "咖啡"],
    scheduled_at: null,
    published_at: null,
    created_at: "2026-03-26T14:00:00Z",
    updated_at: "2026-03-26T14:00:00Z",
  },
];

export const mockTemplates: ContentTemplate[] = [
  {
    id: "t1",
    name: "小红书种草笔记",
    description: "适用于小红书平台的产品种草笔记模板，包含标题公式、正文结构和标签策略",
    platform: "xiaohongshu",
    content_type: "image_post",
    tone: "轻松",
    structure: "标题 + 痛点引入 + 产品亮点 + 使用体验 + 总结推荐",
    example_tags: ["好物分享", "种草", "推荐"],
  },
  {
    id: "t2",
    name: "TikTok 短视频脚本",
    description: "适用于TikTok平台的短视频脚本模板，包含开头钩子、内容节奏和结尾引导",
    platform: "tiktok",
    content_type: "short_video",
    tone: "幽默",
    structure: "钩子开头(3s) + 问题展示 + 解决方案 + 效果展示 + CTA",
    example_tags: ["短视频", "创意", "viral"],
  },
  {
    id: "t3",
    name: "Instagram 轮播图文案",
    description: "适用于Instagram轮播图的文案模板，注重视觉引导和故事叙述",
    platform: "instagram",
    content_type: "carousel",
    tone: "专业",
    structure: "封面标题 + 分页内容要点 + 最终CTA + 标签组合",
    example_tags: ["carousel", "tips", "howto"],
  },
  {
    id: "t4",
    name: "Amazon 产品描述",
    description: "适用于Amazon产品listing的描述模板，突出卖点和SEO关键词",
    platform: "amazon",
    content_type: "article",
    tone: "专业",
    structure: "标题(含关键词) + 5点Bullet Points + 产品描述 + A+内容",
    example_tags: ["listing", "SEO", "转化"],
  },
  {
    id: "t5",
    name: "品牌故事长文",
    description: "适用于品牌独立站的品牌故事内容，传递品牌价值观和情感连接",
    platform: "independent",
    content_type: "article",
    tone: "激励",
    structure: "品牌起源 + 核心理念 + 用户故事 + 未来愿景",
    example_tags: ["品牌故事", "价值观", "情感"],
  },
  {
    id: "t6",
    name: "Shopify 促销活动页",
    description: "适用于Shopify促销活动的页面文案模板，强调紧迫感和优惠力度",
    platform: "shopify",
    content_type: "article",
    tone: "激励",
    structure: "活动主题 + 优惠详情 + 精选商品 + 倒计时 + 购买引导",
    example_tags: ["促销", "限时", "优惠"],
  },
  {
    id: "t7",
    name: "小红书测评笔记",
    description: "适用于小红书平台的产品测评内容，注重真实感和对比分析",
    platform: "xiaohongshu",
    content_type: "article",
    tone: "专业",
    structure: "开箱展示 + 外观评价 + 功能测试 + 优缺点对比 + 购买建议",
    example_tags: ["测评", "真实体验", "对比"],
  },
  {
    id: "t8",
    name: "TikTok 挑战赛脚本",
    description: "适用于TikTok挑战赛的创意脚本模板，注重互动性和传播性",
    platform: "tiktok",
    content_type: "short_video",
    tone: "幽默",
    structure: "挑战介绍 + 规则说明 + 示范演示 + 互动引导 + 标签挑战",
    example_tags: ["挑战赛", "互动", "创意"],
  },
];
