import { KPIData } from "@/lib/types";
import { SkillPack } from "./types";

export const skillsKPIs: KPIData[] = [
  { label: "技能包总数", value: 48, trend: "up", trendPercent: 6.7, icon: "BookOpen", format: "number" },
  { label: "已学习", value: 12, trend: "up", trendPercent: 20.0, icon: "GraduationCap", format: "number" },
  { label: "本周新增", value: 3, trend: "up", trendPercent: 50.0, icon: "Sparkles", format: "number" },
  { label: "热门技能包", value: "TikTok 短视频运营", trend: "up", icon: "Flame" },
];

export const mockSkills: SkillPack[] = [
  {
    id: "sk-001",
    title: "TikTok 短视频运营",
    description: "从账号搭建到爆款视频制作的完整运营流程，涵盖内容策划、拍摄剪辑、发布节奏及数据复盘。",
    category: "operations",
    difficulty: "intermediate",
    icon: "Video",
    usage_count: 1823,
    is_learned: true,
    tags: ["TikTok", "短视频", "爆款"],
    created_at: "2026-01-15T08:00:00Z",
    updated_at: "2026-03-20T10:00:00Z",
    sop_steps: [
      { id: "s1", order: 1, title: "账号定位分析", description: "确定目标受众、内容方向与差异化定位", tips: "先调研 10 个竞品账号", estimated_minutes: 30 },
      { id: "s2", order: 2, title: "内容选题策划", description: "根据热门趋势和用户画像制定选题日历", estimated_minutes: 45 },
      { id: "s3", order: 3, title: "视频拍摄与剪辑", description: "按照脚本完成拍摄，使用模板快速剪辑", estimated_minutes: 60 },
      { id: "s4", order: 4, title: "发布与互动", description: "选择最佳时间发布，积极回复评论提升互动率", estimated_minutes: 20 },
      { id: "s5", order: 5, title: "数据复盘优化", description: "分析播放量、完播率等核心指标，迭代优化内容", estimated_minutes: 30 },
    ],
  },
  {
    id: "sk-002",
    title: "小红书种草笔记写作",
    description: "掌握小红书爆款笔记的写作技巧，包括标题公式、图片排版、标签策略和互动引导。",
    category: "content",
    difficulty: "beginner",
    icon: "PenTool",
    usage_count: 1456,
    is_learned: true,
    tags: ["小红书", "种草", "笔记"],
    created_at: "2026-01-20T08:00:00Z",
    updated_at: "2026-03-18T10:00:00Z",
    sop_steps: [
      { id: "s1", order: 1, title: "选题调研", description: "搜索热门话题和关键词，确定笔记主题", estimated_minutes: 20 },
      { id: "s2", order: 2, title: "标题撰写", description: "运用数字、悬念、对比等公式撰写吸睛标题", estimated_minutes: 10 },
      { id: "s3", order: 3, title: "正文写作", description: "用口语化风格写作，融入个人体验与产品推荐", estimated_minutes: 30 },
      { id: "s4", order: 4, title: "图片制作", description: "制作封面图和内容图，保持统一风格", estimated_minutes: 25 },
    ],
  },
  {
    id: "sk-003",
    title: "亚马逊 Listing SEO 优化",
    description: "系统优化亚马逊产品页面的标题、要点、描述和后端关键词，提升搜索排名和转化率。",
    category: "seo",
    difficulty: "advanced",
    icon: "Search",
    usage_count: 1102,
    is_learned: false,
    tags: ["Amazon", "SEO", "关键词"],
    created_at: "2026-02-01T08:00:00Z",
    updated_at: "2026-03-22T10:00:00Z",
    sop_steps: [
      { id: "s1", order: 1, title: "关键词调研", description: "使用工具挖掘高搜索量、低竞争度的关键词", estimated_minutes: 45 },
      { id: "s2", order: 2, title: "标题优化", description: "按照亚马逊规范编写包含核心关键词的标题", estimated_minutes: 20 },
      { id: "s3", order: 3, title: "要点与描述优化", description: "突出产品卖点并自然嵌入长尾关键词", estimated_minutes: 30 },
    ],
  },
  {
    id: "sk-004",
    title: "Facebook 广告投放入门",
    description: "从零开始学习 Facebook 广告投放，包括受众定位、素材制作、预算分配和效果追踪。",
    category: "ads",
    difficulty: "beginner",
    icon: "Megaphone",
    usage_count: 987,
    is_learned: false,
    tags: ["Facebook", "广告", "投放"],
    created_at: "2026-02-05T08:00:00Z",
    updated_at: "2026-03-15T10:00:00Z",
    sop_steps: [
      { id: "s1", order: 1, title: "广告账户搭建", description: "创建 BM 账户并完成像素安装", estimated_minutes: 30 },
      { id: "s2", order: 2, title: "受众定位设置", description: "根据产品特性选择兴趣、行为和相似受众", estimated_minutes: 25 },
      { id: "s3", order: 3, title: "广告素材制作", description: "制作图片或视频素材，撰写文案", estimated_minutes: 40 },
      { id: "s4", order: 4, title: "数据监控优化", description: "监控 CPC、CTR、ROAS 等指标并优化", estimated_minutes: 20 },
    ],
  },
  {
    id: "sk-005",
    title: "客户差评处理与回复",
    description: "建立高效的客户差评处理流程，包括问题分类、回复模板和客户挽回策略。",
    category: "service",
    difficulty: "intermediate",
    icon: "MessageCircle",
    usage_count: 876,
    is_learned: true,
    tags: ["客服", "差评", "回复"],
    created_at: "2026-02-10T08:00:00Z",
    updated_at: "2026-03-19T10:00:00Z",
    sop_steps: [
      { id: "s1", order: 1, title: "差评分类", description: "按产品质量、物流、服务等维度分类差评", estimated_minutes: 10 },
      { id: "s2", order: 2, title: "模板回复", description: "使用针对性回复模板快速响应客户", estimated_minutes: 15 },
      { id: "s3", order: 3, title: "问题跟进", description: "协调相关部门解决问题并跟进客户满意度", estimated_minutes: 20 },
    ],
  },
  {
    id: "sk-006",
    title: "Instagram Reels 创作指南",
    description: "学习 Instagram Reels 的创作方法论，掌握热门音乐、转场效果和涨粉技巧。",
    category: "content",
    difficulty: "intermediate",
    icon: "Film",
    usage_count: 823,
    is_learned: false,
    tags: ["Instagram", "Reels", "创作"],
    created_at: "2026-02-12T08:00:00Z",
    updated_at: "2026-03-21T10:00:00Z",
    sop_steps: [
      { id: "s1", order: 1, title: "趋势调研", description: "浏览 Reels 热门趋势，收集灵感素材", estimated_minutes: 20 },
      { id: "s2", order: 2, title: "脚本编写", description: "编写 15-30 秒的短视频脚本", estimated_minutes: 15 },
      { id: "s3", order: 3, title: "拍摄与剪辑", description: "利用 Instagram 内置工具拍摄并添加特效", estimated_minutes: 30 },
    ],
  },
  {
    id: "sk-007",
    title: "Shopify 独立站 SEO",
    description: "针对 Shopify 独立站的 SEO 优化策略，包括页面速度、结构化数据、内链建设和博客运营。",
    category: "seo",
    difficulty: "intermediate",
    icon: "Globe",
    usage_count: 756,
    is_learned: false,
    tags: ["Shopify", "SEO", "独立站"],
    created_at: "2026-02-15T08:00:00Z",
    updated_at: "2026-03-17T10:00:00Z",
    sop_steps: [
      { id: "s1", order: 1, title: "技术 SEO 审计", description: "检查页面速度、移动适配和索引状态", estimated_minutes: 40 },
      { id: "s2", order: 2, title: "页面优化", description: "优化 Meta 标签、Alt 文本和 URL 结构", estimated_minutes: 30 },
      { id: "s3", order: 3, title: "内容策略", description: "制定博客内容计划，构建内链体系", estimated_minutes: 35 },
    ],
  },
  {
    id: "sk-008",
    title: "Google Ads 搜索广告优化",
    description: "深入学习 Google Ads 搜索广告的关键词策略、出价优化、广告组结构和质量得分提升。",
    category: "ads",
    difficulty: "advanced",
    icon: "Target",
    usage_count: 694,
    is_learned: false,
    tags: ["Google", "SEM", "广告"],
    created_at: "2026-02-18T08:00:00Z",
    updated_at: "2026-03-16T10:00:00Z",
    sop_steps: [
      { id: "s1", order: 1, title: "关键词策略", description: "根据业务目标选择匹配方式和否定词", estimated_minutes: 35 },
      { id: "s2", order: 2, title: "广告文案优化", description: "撰写高点击率的广告标题和描述", estimated_minutes: 25 },
      { id: "s3", order: 3, title: "出价与预算", description: "设定智能出价策略并合理分配预算", estimated_minutes: 20 },
    ],
  },
  {
    id: "sk-009",
    title: "社媒内容日历管理",
    description: "建立高效的社交媒体内容排期体系，包括选题储备、制作流程和多平台同步发布。",
    category: "operations",
    difficulty: "beginner",
    icon: "Calendar",
    usage_count: 645,
    is_learned: true,
    tags: ["排期", "内容日历", "多平台"],
    created_at: "2026-02-20T08:00:00Z",
    updated_at: "2026-03-14T10:00:00Z",
    sop_steps: [
      { id: "s1", order: 1, title: "月度选题规划", description: "结合营销节点和热点规划每月内容主题", estimated_minutes: 60 },
      { id: "s2", order: 2, title: "内容分配", description: "将选题分配到具体日期和平台", estimated_minutes: 30 },
      { id: "s3", order: 3, title: "制作跟进", description: "跟踪内容制作进度，确保按时交付", estimated_minutes: 20 },
    ],
  },
  {
    id: "sk-010",
    title: "品牌视觉内容设计",
    description: "统一品牌视觉风格，掌握社媒图片设计规范、配色方案和模板复用技巧。",
    category: "content",
    difficulty: "advanced",
    icon: "Palette",
    usage_count: 534,
    is_learned: false,
    tags: ["品牌", "设计", "视觉"],
    created_at: "2026-02-22T08:00:00Z",
    updated_at: "2026-03-13T10:00:00Z",
    sop_steps: [
      { id: "s1", order: 1, title: "品牌风格定义", description: "确定品牌色彩、字体和视觉调性", estimated_minutes: 45 },
      { id: "s2", order: 2, title: "模板库搭建", description: "为不同平台创建可复用的设计模板", estimated_minutes: 60 },
      { id: "s3", order: 3, title: "规范文档", description: "编写品牌视觉使用规范手册", estimated_minutes: 40 },
    ],
  },
  {
    id: "sk-011",
    title: "跨境电商客服话术体系",
    description: "搭建多语言客服话术库，覆盖售前咨询、物流跟踪、退换货处理等常见场景。",
    category: "service",
    difficulty: "beginner",
    icon: "Headphones",
    usage_count: 489,
    is_learned: true,
    tags: ["客服", "话术", "多语言"],
    created_at: "2026-02-25T08:00:00Z",
    updated_at: "2026-03-12T10:00:00Z",
    sop_steps: [
      { id: "s1", order: 1, title: "场景分类", description: "梳理客服常见问题场景", estimated_minutes: 30 },
      { id: "s2", order: 2, title: "话术编写", description: "针对每个场景编写标准话术模板", estimated_minutes: 45 },
      { id: "s3", order: 3, title: "多语言翻译", description: "将话术翻译为目标市场语言", estimated_minutes: 60 },
    ],
  },
  {
    id: "sk-012",
    title: "数据驱动的运营决策",
    description: "学习利用数据分析工具进行运营决策，掌握核心指标体系、AB 测试方法和归因分析。",
    category: "operations",
    difficulty: "advanced",
    icon: "BarChart3",
    usage_count: 412,
    is_learned: false,
    tags: ["数据", "分析", "决策"],
    created_at: "2026-03-01T08:00:00Z",
    updated_at: "2026-03-25T10:00:00Z",
    sop_steps: [
      { id: "s1", order: 1, title: "指标体系搭建", description: "建立北极星指标和关键结果指标体系", estimated_minutes: 45 },
      { id: "s2", order: 2, title: "数据看板配置", description: "配置自动化数据看板追踪核心指标", estimated_minutes: 35 },
      { id: "s3", order: 3, title: "AB 测试设计", description: "设计实验方案，制定测试计划", estimated_minutes: 30 },
      { id: "s4", order: 4, title: "归因分析", description: "分析渠道贡献度，优化资源分配", estimated_minutes: 40 },
    ],
  },
];
